
version: '3.8'

services:
  builder:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: pocket_server_builder
    volumes:
      - .:/app
    environment:
      - ANDROID_SDK_ROOT=/opt/android-sdk
    command: tail -f /dev/null # 컨테이너를 계속 띄워두기 위함
